# Site
repository: JinHyukParkk/JinHyukParkk.github.io

favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박진혁
title: 백엔드 개발자
email: pjh08190819@gmail.com
website: https://blog.naver.com/pjh08190819

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: jinhyukparkk
linkedin_username: 진혁-박-504777130
instagram_username: hyuk_eea
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/hyuk2.jpeg
about_content: | # this will include new lines to allow paragraphs
  **'노력이 없으면 발전도 없다. ’** 항상 배우는 자세를 잃지 않는 개발자입니다.<br/>
  <br/>
  현재 5년차 <mark>Java 백엔드 개발자</mark>로 있습니다.<br/>
  <br/>
  **새로운 시도**에 <mark>주도적</mark>이고, 습득한 내용은 <mark>기록</mark>합니다. <br/>
  <br/>
  **문제 해결**이라면 밤낮 가리지 않고, 해결하려는 <mark>집요함</mark>이 있습니다. <br/>
  <br/>
  <mark>함께 자라는 개발 문화</mark>를 중시하여 팀원들과 소통하고, 학습하고, 개선하는 것을 좋아합니다.

#You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: 보유 기술     
    layout: list
    content:
      - layout: left
        title: Backend
        description: |
          * Java, Groovy, PHP
          * Spring Boot, Batch, JPA
          * Junit5
          * Gradle, Maven
          * MySQL, MariaDB, MongoDB, AWS S3
          * Redis, ElasticSearch
          * Trino, Minio

      - layout: left
        title: DevOps / System
        description: |
          * Jira, Slack, Discord
          * Jenkins, GitLab-CI, TravisCI
          * nGrinder, Sentry
          * Nginx
          * Docker, Kubernetes

      - layout: left
        title: Frontend
        description: | 
          * Html, Javascript
          * Handlebars

  - title: 경력 사항 
    layout: list
    content:
      - layout: left
        title: 아프리카TV 광고 서비스
        caption: 2022.01 ~ 현재
        description: | 
          * 아프리카TV 광고 안내 서비스 PHP -> Java 컨버팅 (Spring boot)
          * 아프리카TV 광고 단가 배치 PHP -> Java 컨버팅 (Spring batch)
          * 리타겟팅 광고를 위한 맞춤 타겟 서비스 개발

      - layout: left
        title: 아프리카TV 검색 서비스
        caption: 2020.01 ~ 2022.05
        description: | 
          * 아프리카TV 검색 API 개발
          * 아프리카TV 검색 시스템 구조 개선
          * ElasticSearch 검색 데이터 인덱서 개발
          * ElasticSearch 한글 형태소 분석기 튜닝
          * ElasticSearch 7.17.4 버전 업그레이드 / 운영 개선
          * Cache, Storage 용도 Redis Cluster 구조 설계 / 성능 개선 / 운영
          * WhaTap / nGrinder을 통한 성능 테스트 및 개선
          * Jira / Gitlab-CI / Slack / Sentry 를 이용한 작업 배포 자동화, 에러 트레킹, 이슈 모니터링 알림 CI 구축

      - layout: left
        title: 아프리카TV 전사 서비스
        caption: 2018.05 ~ 2019.12
        description: | 
          * 신입BJ 지원센터 - 포인트 구조 설계 / 서비스 API, Batch 개발 및 운영
          * MCN youtube 수익 정산 어드민 / 서비스 관리
          * 아프리카TV 게시판 개발 / 유지보수
          * 상시 이벤트 페이지 개발

      - layout: left
        title: 한국전자통신연구원(Etri)
        link: https://www.etri.re.kr/intro.html
        sub_title: 연구연수생
        caption: 2018.1 ~ 2018.2
        
        # quote: >
        #   과학기술정보통신부 산하 과학기술분야 정부출연연구기관
        description: | # this will include new lines to allow paragraphs
          * 공간 정보 데이터에 관련된 과제를 진행하였습니다. <br/>
          1. <a href="https://github.com/JinHyukParkk/DownloadTile">Naver, Daum, Vworld Map에서 위성 Tile을 받아오기</a> (golang) <br/>
          2. <a href="https://github.com/JinHyukParkk/resolution-TileSize-comparison">위성 Tile들의 해상도를 낮추어 파일 크기를 비교</a> (golang) <br/>
          3. <a href="https://github.com/JinHyukParkk/Building-Infomation">Vworld Map의 3D 건물 텍스쳐 정보 리스트 추출하기</a> (C#)
          
      - layout: left
        title: 모비젠
        link: http://www.mobigen.com/
        sub_title: DevOps 엔지니어 인턴
        caption: 2017.1 ~ 2017.6
        
        # quote: >
        #   빅데이터 구축 및 분석 전문으로 빅데이터 기술을 제공하는 ICT솔루션 기업
        description: | # this will include new lines to allow paragraphs
          * 하둡 에코 시스템 설치 자동화를 위한 스크립트 작성과
          * Docker, Kubernetes 구축 / 기술 밴치마킹을 진행하였습니다. <br/>
          1. <a href="https://www.slideshare.net/ssuser4921ff/kubernetes-79834978">Kubernetes 설치 발표 자료</a> <br/>
          2. <a href="https://www.slideshare.net/ssuser4921ff/keepalived-haproxy">keepalived, Haproxy 발표 자료</a> <br/>
          3. <a href="https://www.slideshare.net/ssuser4921ff/git-server-git-olitegitweb-79832661">Git 서버 구축 발표 자료</a>

      # - layout: top-middle
      #   title: 아프리카TV 광고 서비스
      #   quote: >
      #     2021.01 ~ 현재
      #   description: | 
      #     * 아프리카TV 광고 안내 서비스 PHP -> JAVA 컨버팅

  - title: 토이 프로젝트
    layout: list
    content:
      - layout: left
        title: 코토방
        link: https://github.com/JinHyukParkk/project-spring-4-JinHyukParkk
        sub_title: 각 코인 종목 토론을 위한 게시판
        caption: 2022.01 ~ 2022.03
        description: | 
          * 개발 환경 : Java11, Spring Boot(2.6.3), MySQL, Apache Tomcat
          * Upbit API 사용하여 코인 정보 불러오기
          * Junit5 계층 구조 테스트 코드 적용
          * JPA를 활용한 ORM 방식 개발
          * RestFul API 구현

      - layout: left
        title: 너의 주식을 위해
        link: https://github.com/JinHyukParkk/forYourStock
        sub_title: 친구 메일로 회사 공시 보내주기
        caption: 2020.09 ~ 2020.10
        description: | # this will include new lines to allow paragraphs
          * 개발 환경 : Golang(1.13), CentOs7
          * dart API 사용하여 등록된 회사 정보 / 공시 불러오기
          * SMTP를 이용한 메일 전송 구현
          * 8시 30분마다 프로그램 실행을 위한 Crontab 설정

  - title: 외부 활동
    layout: list
    content: 
      - layout: left
        title: 코드숨 커뮤니티
        caption: 2021.12 ~ 현재
        description: | 
          * 코드숨 스프링 4기 수강
          * 개발 스터디, 코드 리뷰, 피드백, 문화 공유

  - title: 관련 링크
    layout: list
    content: 
      - layout: top-middle
        title: 학부 프로젝트
        caption: 2012.03 ~ 2018.08
        link: https://aerial-skirt-dc1.notion.site/9246d1c88c0141579126aa88b90d165f
        link_text: 클릭

          
#  - title: Education # Title for the section
#    layout: list  # Type of content section (list/text)
#    content: # this will include new lines to allow paragraphs
#      - layout: top-right
#        title: Institution name
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)
#        quote: >
#          Short institution or course description (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of qualification
  #  link: 
    #  link_text: 
    #  additional_links:
    #    - title:  Github page for project (eg. sproogen/modern-resume-theme)
    #      icon: fab fa-github
    #      url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    #    - title:  Github page for project (eg. sproogen/modern-resume-theme)
    #      icon: fab fa-github
    #      url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
